language: ruby
env:
  global:
    - FA_PUBLIC_FOLDER=http://localhost:3000
rvm:
  - 2.3.1
services:
  - postgresql
addons:
  postgresql: "9.4"
before_install:
  - gem install bundler -v 1.17.3
  - bundle install
  - RAILS_ENV=test bundle exec rake db:create db:schema:load
